/**
 * AWE Player - Main Entry Point for Phase 8 Web Audio Integration
 * 
 * Phase 8B Focus: Complete Web Interface
 * - Initialize WASM module
 * - Set up organized UI controls
 * - Test complete browser playback pipeline
 */

import { DebugLogger } from './utils/debug-logger.js';
import { UIControlManager } from './ui-controls.js';

// Create debug logger instance for main application
const logger = new DebugLogger({ componentName: 'Main', enabled: true });

// Global state
let wasmModule: any = null;
let uiControlManager: UIControlManager | null = null;

/**
 * Initialize the application
 */
async function main(): Promise<void> {
    try {
        logger.log('🚀 AWE Player starting - Phase 8B Complete Web Interface');
        
        // Step 1: Load WASM module
        await initializeWASM();
        
        // Step 2: Initialize UI Control Manager
        uiControlManager = new UIControlManager(wasmModule);
        uiControlManager.initialize();
        
        logger.log('✅ AWE Player initialization complete');
        
    } catch (error) {
        logger.log('❌ Failed to initialize AWE Player', error);
        
        // Update status directly since UI manager might not be available
        const wasmStatus = document.getElementById('wasm-status') as HTMLElement;
        const audioStatus = document.getElementById('audio-status') as HTMLElement;
        const workletStatus = document.getElementById('worklet-status') as HTMLElement;
        
        if (wasmStatus) wasmStatus.textContent = 'WASM: Error';
        if (audioStatus) audioStatus.textContent = 'Audio: Failed';
        if (workletStatus) workletStatus.textContent = 'AudioWorklet: Failed';
    }
}

/**
 * Load and initialize the WASM module
 */
async function initializeWASM(): Promise<void> {
    try {
        logger.log('📦 Loading WASM module...');
        
        // Import WASM module (generated by wasm-pack)
        const wasmPkg = await import('./wasm-pkg/awe_synth.js');
        await wasmPkg.default(); // Initialize WASM
        
        wasmModule = wasmPkg;
        
        logger.log('✅ WASM module loaded successfully');
        
    } catch (error) {
        throw new Error(`Failed to load WASM module: ${error}`);
    }
}

// Start the application
main().catch(error => {
    console.error('💥 Fatal error during initialization:', error);
    
    // Update status directly since UI manager might not be available
    const wasmStatus = document.getElementById('wasm-status') as HTMLElement;
    if (wasmStatus) {
        wasmStatus.textContent = 'WASM: Fatal Error';
        wasmStatus.className = 'status-item error';
    }
});

export { }; // Make this a module